---
- name: Ensure Neovim build dependencies are installed.
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: "{{ neovim_packages }}"
    state: present
    install_recommends: false

- name: Install linter for Lua.
  ansible.builtin.command: luarocks install luacheck
  args:
    creates: /usr/local/bin/luacheck
