---
- name: Ensure Neovim build dependencies are installed.
  become: true
  ansible.builtin.apt:
    update_cache: true
    name: "{{ neovim_packages }}"
    state: present
    install_recommends: false
